server:
  port: 8080
  address: 0.0.0.0
  
spring:
  application:
    name: booking
        
  data:
    jpa:
      repositories.enabled: true
      
      
  jpa:
    properties:
      hibernate.max_fetch_depth: 3
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.fetch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.enable_lazy_load_no_trans: true
      
    hibernate:
      open-in-view: true
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://149.28.145.135:3306/scb_test
    username: prasit
    password: gody6707
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000 
      maximum-pool-size: 50
      
info:
  application:
    name: '@project.name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
    scm-url: "@scm.url@"

logging:
  level:
    org.hibernate.jpa.internal.util.LogHelper: DEBUG
    